server_port: 8080
tapp_url: "https://display-engine-mirror.tapp-dex.devucc.name/api/v1"
db_config:
  url: "postgresql://username:password@neon_host/db_name"
  pool_size: 25
stream_config:
  indexer_grpc: "https://grpc.mainnet.aptoslabs.com:443"
  # Go to https://developers.aptoslabs.com/ to create a project and get an API token
  auth_token: "auth_token_you_can_get_from_aptos_build"
  # Default tx version to start indexing
  starting_version: 1645629573
nft_marketplace_configs:
  - name: topaz
    # At which tx version to start indexing the marketplace, usually this is the tx version when the contract was deployed
    starting_version: 1645629573
    contract_address: 0x2c7bccf7b31baf770fdbcc768d9e9cb3d87805e255355df5db32ac9a669010a2
    event_model_mapping:
      events::ListEvent: list
      events::DelistEvent: unlist
      events::BuyEvent: buy
      events::BidEvent: solo-bid
      events::CancelBidEvent: unlist-bid
      events::SellEvent: accept-bid
      events::CollectionBidEvent: collection-bid
      events::FillCollectionBidEvent: accept-collection-bid
      events::CancelCollectionBidEvent: cancel-collection-bid
    events:
      events::ListEvent:
        event_fields:
          "$.listing_id":
            - table: nft_marketplace_activities
              column: listing_id
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount

      events::DelistEvent:
        event_fields:
          "$.listing_id":
            - table: nft_marketplace_activities
              column: listing_id
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
      
      events::BuyEvent:
        event_fields:
          "$.listing_id":
            - table: nft_marketplace_activities
              column: listing_id
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
      
      events::BidEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column: offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time

      events::CancelBidEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column: offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time

      events::SellEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column: offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time
      
      events::CollectionBidEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column: collection_offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time

      events::FillCollectionBidEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column:  collection_offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.seller":
            - table: nft_marketplace_activities
              column: seller
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.token_id.token_data_id.name":
            - table: nft_marketplace_activities
              column: token_name
          "$.token_id.token_data_id.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.token_id.token_data_id.collection":
            - table: nft_marketplace_activities
              column: collection_name
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time

      events::CancelCollectionBidEvent:
        event_fields:
          "$.bid_id":
            - table: nft_marketplace_activities
              column: collection_offer_id
          "$.amount":
            - table: nft_marketplace_activities
              column: token_amount
          "$.buyer":
            - table: nft_marketplace_activities
              column: buyer
          "$.price":
            - table: nft_marketplace_activities
              column: price
          "$.creator":
            - table: nft_marketplace_activities
              column: creator_address
          "$.collection_name":
            - table: nft_marketplace_activities
              column: collection_name
          "$.deadline":
            - table: nft_marketplace_activities
              column: expiration_time